import Head from "next/head";
import { useRouter } from "next/router";
import Button from "~/components/Button";
import { api } from "~/utils/api";

export default function Home() {
  const router = useRouter();
  const createGame = api.games.create.useMutation();

  const handleCreateGame = () => {
    createGame.mutate(undefined, {
      onSuccess: (data) => {
        console.log("data", data);
        void router.push({
          pathname: "/game/[id]",
          query: { id: data.id },
        });
      },
    });
  };

  return (
    <>
      <Head>
        <title>Welcome. Please create a new game to continue.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="mb-5 text-amber-500">
          Please create a new game to continue
        </h1>
        <Button onClick={handleCreateGame}>Create a new game</Button>
      </main>
    </>
  );
}
