import Head from "next/head";
import { useRouter } from "next/router";
import Button from "~/components/Button";
import { api } from "~/utils/api";
import Heading from "../../components/Heading";
import PageWrapper from "../../components/PageWrapper";

export default function Home() {
  const router = useRouter();
  const createGame = api.games.create.useMutation();

  const handleCreateGame = () => {
    createGame.mutate(undefined, {
      onSuccess: (data) => {
        console.log("data", data);
        void router.push({
          pathname: "/game/[id]",
          query: { id: data.id },
        });
      },
    });
  };

  return (
    <>
      <Head>
        <title>Welcome. Please create a new game to continue.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <Heading>Please create a new game to continue</Heading>
        <Button onClick={handleCreateGame}>Create a new game</Button>
      </PageWrapper>
    </>
  );
}
